# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/markdownlint/markdownlint
    rev: b72d1808dfe51b669ef91d6abf8b904505c22c9b
    hooks:
      - id: markdownlint_docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.8.0
    hooks:
      - id: hadolint-docker
  - repo: local
    hooks:
      - id: format python
        name: format python
        entry: poetry run format
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
      - id: lint python
        name: lint python
        entry: poetry run lint
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
      - id: test
        name: test
        entry: poetry run test
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
